name: Respond to approved

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-state:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Find last comment
        id: find-last-comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          comment-author: 'github-actions[bot]'
          body-includes: 'Change for master is approved!!'

      - name: Comment
        if: steps.find-last-comment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: "ä½œæ¥­ãŒæ‰¿èªã•ã‚Œã¾ã—ãŸï¼ğŸ‰
          ---
          * æ…é‡ã«  `Merge pull reguest â–¼` ã‚’å®Ÿè¡Œã—ã¦ãã ã•ã„`
          * Mergeå¾Œã€[ã‚¹ãƒ†ãƒ¼ã‚¸ãƒ³ã‚°ç’°å¢ƒ](https://qiita.com/okazy/items/7ab46f2c20ec341a2836)ã§ã®å‹•ä½œç¢ºèªã—ã¦ãã ã•ã„
          * å‹•ä½œç¢ºèªãŒå•é¡Œãªã‘ã‚Œã°[æœ¬ç•ªåŒ–ç”¨ã®ãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆ](https://github.com/mu7kata/action_game/pull/9)ã‚’ä½œæˆã—æœ¬ç•ªåŒ–ã—ã¦ãã ã•ã„
          "
